[bosun]
exclude_ips = [ "192.168.168.168" ]
discovery = [ "docker", "static" ]
push_pull_interval = "20s"

[docker_discovery]
docker_url = "unix://var/run/docker.sock"

[static_discovery]
config_file = "static.json"

[services]
name_match = "^/(.+)(-[0-9a-z]{7,14})$"

[haproxy]
bind_ip       = "192.168.168.168"
template_file = "views/haproxy.cfg"
config_file   = "/etc/haproxy.cfg"
