[sidecar]
exclude_ips = [ "192.168.168.168" ]
discovery = [ "docker" ]
push_pull_interval = "20s"
default_check_endpoint = "/version"
logging_level = "info"
gossip_messages = 15

[docker_discovery]
docker_url = "unix:///var/run/docker.sock"

[services]
namer = "docker_label"
name_label = "ServiceName"

[haproxy]
bind_ip       = "192.168.168.168"
template_file = "views/haproxy.cfg"
config_file   = "/etc/haproxy.cfg"
pid_file      = "/var/run/haproxy.pid"
user          = "haproxy"
group         = "haproxy"

[listeners]
urls = [ "http://192.168.168.168:7778/update" ]
